apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::719737572889:role/codebuild-deploy-to-eks-service-role
      username: codebuild
      groups:
        - system:masters
    - rolearn: arn:aws:iam::719737572889:role/codebuild-deploy-to-eks-service-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

