apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    # CodeBuild role for deploying to EKS
    - rolearn: arn:aws:iam::719737572889:role/codebuild-deploy-to-eks-service-role
      username: codebuild
      groups:
        - system:masters

    # EC2 NodeInstanceRole for joining EKS worker nodes
    - rolearn: arn:aws:iam::719737572889:role/eksctl-your-nodegroup-role-name
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

