version: 0.2

phases:
  pre_build:
    commands:
      - echo Hello World
      - echo Starting build

  build:
    commands:
      - echo Building
      - echo Build complete

  post_build:
    commands:
      - echo Post build
      - echo Done

artifacts:
  files:
    - appspec.yml
  discard-paths: yes 
