version: 0.2

phases:
  pre_build:
    commands:
      - chmod +x build.sh

  build:
    commands:
      - ./build.sh

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - taskdef.json
  discard-paths: yes 