apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: brain-tasks-cluster
  region: us-east-1
  version: '1.28'

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true
        albIngress: true

# Enable OIDC provider for IAM roles
iam:
  withOIDC: true

# Add ECR access
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest 
